version: '3.8'

services:
  auth_service:
    build:
      context: ./auth_service
    container_name: auth_service
    ports:
      - "8000:8000"
    env_file:
      - ./auth_service/.env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: